export const mockNoteList = [
  {
    id: "1",
    title: "纽约",
    noteType: "image",
    noteCover: ["/images/travel1.jpg"],
    avatar: "https://picsum.photos/100",
    username: "Alice",
    likeCount: 123,
    categoryId: "1",
    content: "到达纽约最高楼",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "2",
    title: "广东蟑螂很担心你",
    noteType: "image",
    noteCover: ["/images/home1.jpg"],
    avatar: "https://picsum.photos/200",
    username: "Bob",
    likeCount: 98,
    categoryId: "2",
    content: "是广州番禺广场旁边的中国银行大厦",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "3",
    title: "茶理宜世和广州动物园联动",
    noteType: "image",
    noteCover: ["/images/activity1.jpg"],
    avatar: "https://picsum.photos/300",
    username: "Charlie",
    likeCount: 100,
    categoryId: "3",
    content: "买了一个联动的小熊猫金属徽章",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "4",
    title: "新加坡动物园的狐猴",
    noteType: "image",
    noteCover: ["/images/travel2.jpg"],
    avatar: "https://picsum.photos/400",
    username: "Daniel",
    likeCount: 567,
    categoryId: "1",
    content: "可以近距离接触，票价很值",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "5",
    title: "中珠假期找旅伴（限女生版",
    noteType: "image",
    noteCover: ["/images/travel8.png"],
    avatar: "https://picsum.photos/1600",
    username: "Oliver",
    likeCount: 66,
    categoryId: "1",
    content: "中珠假期找旅伴，限女生，去上海/哈尔滨/成都，有意向可以私戳我！",
    tag: ["上海","哈尔滨","成都","找旅伴"],
    datetime: "2024-11-27 12:12:12",
    collection: "20",
    comment: "0",
  },
  {
    id: "6",
    title: "重返未来1999快闪店",
    noteType: "image",
    noteCover: ["/images/activity2.jpg"],
    avatar: "https://picsum.photos/600",
    username: "Felix",
    likeCount: 321,
    categoryId: "3",
    content: "你说得对，但是乌拉圭的人口有345.7万，同时，仅澳大利亚就有4700万只袋鼠。 如果袋鼠决定入侵乌拉圭，那么每一个乌拉圭人要打14只袋鼠，你不知道，你不在乎，你只关心你自己\n" +
      "\n" +
      "你说得对，但是梵蒂冈人口只有801人，同时仅澳大利亚就有4700万只袋鼠。如果袋鼠决定入侵梵蒂冈，每个梵蒂冈人要打58676只袋鼠，你不知道，你不在乎，你只关心乌拉圭\n" +
      "\n" +
      "你说得对，但是西兰公国人口只有22人，同时仅澳大利亚就有4700万只袋鼠。如果袋鼠决定入侵西兰公国，每个西兰公国人要打2136363 只袋鼠，你不知道，你不在乎，你只关心梵蒂冈\n" +
      "\n" +
      "你说得对，但是加尔撒哈拉王国人口只有3人，同时仅澳大利亚就有4700万只袋鼠。如果袋鼠决定入侵加尔撒哈拉王国，每个加尔撒哈拉人要打15,666,666.66666667 只袋鼠，你不知道，你不在乎，你只关心西兰公国\n" +
      "\n" +
      "你说得对，但是中国的人口有14亿，同时，仅澳大利亚就有4700万只袋鼠。 如果袋鼠决定入侵中国，那么每一个袋鼠要打30个中国人，你不知道，你不在乎，你只关心撒哈拉\n" +
      "\n" +
      "你说得对，但是当弗朗西斯科·索拉诺·洛佩兹上台的时候，拥有133.7万人口的巴拉圭只剩下22.1万人了，连给他洗内裤的人都没了，乌拉圭的人口却有345.7万，如果乌拉圭人决定入侵巴拉圭，那么每一个巴拉圭人要打15个乌拉圭人；如果袋鼠决定入侵巴拉圭，每一个巴拉圭人要打210只袋鼠。可是你不知道，你不在乎，你只关心乌拉圭。\n" +
      "\n" +
      "你说的对，但是你自己只有1个人，仅澳大利亚就有4700万只袋鼠，所以袋鼠决定入侵你家。等着吧",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "7",
    title: "滨海湾花园",
    noteType: "image",
    noteCover: ["/images/travel3.jpg"],
    avatar: "https://picsum.photos/700",
    username: "George",
    likeCount: 135,
    categoryId: "1",
    content: "非常好景点，爱来自瓷器，非常好环境，爱来自广阔的东边，非常好植物，爱来自珍珠的海洋，非常好花卉，爱来自香味的洲际，非常好猪笼草，爱来自中间的珍珠",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "8",
    title: "广州某街道",
    noteType: "image",
    noteCover: ["/images/home3.jpg"],
    avatar: "https://picsum.photos/800",
    username: "Harry",
    likeCount: 987,
    categoryId: "2",
    content: "我也不知道在哪，应该是海珠区或者荔湾区",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "9",
    title: "逛公园",
    noteType: "image",
    noteCover: ["/images/activity3.jpg"],
    avatar: "https://picsum.photos/900",
    username: "Ivan",
    likeCount: 678,
    categoryId: "3",
    content: "我也不知道这是哪，因为这图不是我的",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "10",
    title: "好莱坞环球影城的马里奥饮品",
    noteType: "image",
    noteCover: ["/images/travel4.jpg"],
    avatar: "https://picsum.photos/1000",
    username: "James",
    likeCount: 135,
    categoryId: "1",
    content: "这一杯花了我折合人民币100元",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "11",
    title: "番禺广场",
    noteType: "image",
    noteCover: ["/images/home4.jpg"],
    avatar: "https://picsum.photos/1100",
    username: "Kevin",
    likeCount: 987,
    categoryId: "2",
    content: "顺带吐槽一个月没回家，回个家发现番禺广场不是起终点站了",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "12",
    title: "珠海航展",
    noteType: "image",
    noteCover: ["/images/activity4.jpg"],
    avatar: "https://picsum.photos/1200",
    username: "Lily",
    likeCount: 678,
    categoryId: "3",
    content: "我没去，图偷的",
    tag: [],
    collection: "60",
    comment: "0",
  },
  {
    id: "13",
    title: "好莱坞环球影城马里奥园区",
    noteType: "video",
    noteCover: ["/images/travel5.jpg"],
    video: "/images/travel5.mp4",
    avatar: "https://picsum.photos/1300",
    username: "Mario",
    likeCount: 66666,
    categoryId: "1",
    content: "好玩",
    tag: [],
    collection: "666",
    comment: "0",
  },
  {
    id: "14",
    title: "哈佛和麻省理工",
    noteType: "image",
    noteCover: ["/images/travel6.jpg","/images/travel7.jpg"],
    avatar: "https://picsum.photos/1500",
    username: "Nancy",
    likeCount: 12345,
    categoryId: "1",
    content: "蹭大佬的地盘",
    tag: [],
    collection: "666",
    comment: "0",
  },

  {
    id: "15",
    title: "广州某小巷",
    noteType: "image",
    noteCover: ["/images/home2.jpg"],
    avatar: "https://picsum.photos/500",
    username: "Emily",
    likeCount: 666,
    categoryId: "2",
    content: "我也不知道在哪，应该是海珠区或者荔湾区",
    tag: [],
    collection: "60",
    comment: "0",
  },
];


export const mockCategoryList = [
  { id: "1", title: "旅行" },
  { id: "2", title: "返乡" },
  { id: "3", title: "外出活动" },
];
